Re-initialize the transient fields in readResolve
Added a test, without readResolve patch test fails with NPE
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.776 s <<< FAILURE! -- in com.google.jenkins.plugins.computeengine.InstanceConfigurationTest
[ERROR] com.google.jenkins.plugins.computeengine.InstanceConfigurationTest.testTransientZoneStateSurvivesDeserialization -- Time elapsed: 4.617 s <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ConcurrentHashMap.get(Object)" because "this.exhaustedAt" is null
        at com.google.jenkins.plugins.computeengine.InstanceConfiguration.isExhausted(InstanceConfiguration.java:507)
        at com.google.jenkins.plugins.computeengine.InstanceConfigurationTest.testTransientZoneStateSurvivesDeserialization(InstanceConfigurationTest.java:684)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   InstanceConfigurationTest.testTransientZoneStateSurvivesDeserialization:684 » NullPointer Cannot invoke "java.util.concurrent.ConcurrentHashMap.get(Object)" because "this.exhaustedAt" is null
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```