transient field re-initialize test to use `@LocalData`
Fails with the readResolve patch as,

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.989 s <<< FAILURE! -- in com.google.jenkins.plugins.computeengine.InstanceConfigurationTest
[ERROR] com.google.jenkins.plugins.computeengine.InstanceConfigurationTest.testZoneExhaustionStateTransientFieldInitializedAfterLoad -- Time elapsed: 3.815 s <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ConcurrentHashMap.get(Object)" because "this.exhaustedAt" is null
        at com.google.jenkins.plugins.computeengine.InstanceConfiguration.isExhausted(InstanceConfiguration.java:507)
        at com.google.jenkins.plugins.computeengine.InstanceConfigurationTest.testZoneExhaustionStateTransientFieldInitializedAfterLoad(InstanceConfigurationTest.java:683)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   InstanceConfigurationTest.testZoneExhaustionStateTransientFieldInitializedAfterLoad:683 » NullPointer Cannot invoke "java.util.concurrent.ConcurrentHashMap.get(Object)" because "this.exhaustedAt" is null
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
```