Support handling ZONE_RESOURCE_POOL_EXHAUSTED errors by allowing multiple fallback options (#555)
* Support fallback zone for ZONE_RESOURCE_POOL_EXHAUSTED

* hard code the zones for clear demostration in tests

* fix the rezone logic, simplify operation error handling

* no need add the license

* spotbugs reason

* fix spotless

* make the integration test fallback to second fallbackZone to verify the splitting is correct

* address copilot's reviews

* bug fix in handling existing disk rezoning to targetzone

* no need of zoneOverride setting in the instance method, already handled in rezone method

* add javadoc about the provision and provisionWithFallback

* update the documentation

* move the vm provisioning and fallback logic to the future

* ssh credential race condition fix

* some improvements to the code no behavior change

* additional defenses

* fix double thread in fallback path by extracting logic into common method and resuing

* track exhausted zones in a transient field, use single provision path for with/without fallback zone

* skip instance configuration and eventually the cloud itself so the item moves to differnt cloud

* restore private on uniquename method

* fix the wordings in the fallback zone region relationship

* reduce diff inline the buildNode method

* Re-initialize the transient fields in readResolve

Added a test, without readResolve patch test fails with NPE
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.776 s <<< FAILURE! -- in com.google.jenkins.plugins.computeengine.InstanceConfigurationTest
[ERROR] com.google.jenkins.plugins.computeengine.InstanceConfigurationTest.testTransientZoneStateSurvivesDeserialization -- Time elapsed: 4.617 s <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ConcurrentHashMap.get(Object)" because "this.exhaustedAt" is null
        at com.google.jenkins.plugins.computeengine.InstanceConfiguration.isExhausted(InstanceConfiguration.java:507)
        at com.google.jenkins.plugins.computeengine.InstanceConfigurationTest.testTransientZoneStateSurvivesDeserialization(InstanceConfigurationTest.java:684)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   InstanceConfigurationTest.testTransientZoneStateSurvivesDeserialization:684 » NullPointer Cannot invoke "java.util.concurrent.ConcurrentHashMap.get(Object)" because "this.exhaustedAt" is null
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

* update the readme with fallback behavior details

* Add new ITs and update doc

New IT tests are added and tested that demostrate the multiple configuration fallback happens on capacity error, and even multiple cloud fallback happens on capacity errors

* transient field re-initialize test to use `@LocalData`

Fails with the readResolve patch as,

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.989 s <<< FAILURE! -- in com.google.jenkins.plugins.computeengine.InstanceConfigurationTest
[ERROR] com.google.jenkins.plugins.computeengine.InstanceConfigurationTest.testZoneExhaustionStateTransientFieldInitializedAfterLoad -- Time elapsed: 3.815 s <<< ERROR!
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ConcurrentHashMap.get(Object)" because "this.exhaustedAt" is null
        at com.google.jenkins.plugins.computeengine.InstanceConfiguration.isExhausted(InstanceConfiguration.java:507)
        at com.google.jenkins.plugins.computeengine.InstanceConfigurationTest.testZoneExhaustionStateTransientFieldInitializedAfterLoad(InstanceConfigurationTest.java:683)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   InstanceConfigurationTest.testZoneExhaustionStateTransientFieldInitializedAfterLoad:683 » NullPointer Cannot invoke "java.util.concurrent.ConcurrentHashMap.get(Object)" because "this.exhaustedAt" is null
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
```

* Update README.adoc

* add fine level log statements

* remove unnecessary long sentence from readme - short sentences

* log all the error codes and their messages when operations error happens